-- Seed agenda Informaciones ASLI desde contacts_corregidos.csv
-- 139 contactos

WITH grupo AS (
  SELECT id FROM public.informaciones_grupos WHERE nombre = 'Informaciones ASLI' LIMIT 1
),
ins AS (
  INSERT INTO public.informaciones_contactos (nombre, email, empresa)
  VALUES
  ('ABRAHAM QUEZADA', 'abraham.quezada@naturesouth.cl', 'NATURE SOUTH'),
  ('AGUSTIN WEASON', 'aweason@redstar.cl', 'RED STAR'),
  ('ALEJANDRA CANCLINI', 'acanclini@briza.cl', 'BRIZA'),
  ('ALEJANDRA GONZALEZ', 'alejandra.gonzalez@salmonesaustral.cl', 'SALMONES AUSTRAL'),
  ('ALEJANDRO NEIRA', 'aneira@briza.cl', 'BRIZA'),
  ('ALEX ASTUDILLO', 'aastudillo@quintayfruit.cl', 'QUINTAY FRUIT'),
  ('ALEX MARTINEZ', 'alexis.martinez@goldanda.cl', 'GOLD ANDA CHILE'),
  ('ALEX PAREDES', 'alex.paredes@cermaq.com', 'CERMAQ'),
  ('ALEXIS ALVARADO', 'alexis.alvarado@oxzo.cl', 'OXZO'),
  ('ALFONSO FRIAS', 'afrias@blossom.cl', 'BLOSSOM EXPORT'),
  ('ALFONSO NAGUIAN', 'anaguian@caletabay.cl', 'CALETA BAY'),
  ('ALFREDO', 'alfredo@farawayland.cl', 'FARAWAY LAND'),
  ('ALMAFRUIT EXPORT', 'almafruitexport@gmail.com', NULL),
  ('ALONSO SALGADO', 'alonso.salgado@vrfoods.cl', 'VR FOODS'),
  ('ALVARO LARRONDO', 'alarrondo@terrafrut.cl', 'TERRAFRUT'),
  ('ANDRE COURTIN', 'andre.courtin@greenex.cl', 'GREENEX'),
  ('ANDREA GONZALEZ', 'andrea.gonzalez@esperanza-verde.com', 'ESPERANZA VERDE'),
  ('ANDRÉS HEDERRA', 'ahederra@gmail.com', 'ALMAFRUIT'),
  ('ANDRES MANSILLA', 'andres@aqua-link.cl', 'AQUALINK'),
  ('ANDRÉS MIRANDA', 'amiranda@jotrisa.cl', 'JOTRISA'),
  ('ANGELO LAGOS', 'angelolagos@sglchile.com', 'SGL CHILE'),
  ('ANIBAL CAMINITTI', 'gerenciacapci@gmail.com', 'CAPCI'),
  ('ANTONIA OYARZÚN', 'antonia.oyarzun@copefrut.com', 'COPEFRUT'),
  ('ANTONIA PINOCHET', 'aipinoch@uc.cl', 'AGRÍCOLA INDEPENDENCIA'),
  ('ANTONIO VERA', 'antonio.vera@aysenpacific.com', 'AYSEN PACIFIC'),
  ('ARIEL GALLEGUILLOS', 'agalleguillos@cylfruit.com', 'C&L FRUIT'),
  ('AUGUSTO FRIAS', 'augustofrias@blossom.cl', 'BLOSSOM EXPORT'),
  ('BENJAMIN CARDOEN', 'benjamincardoen@sanandresexport.cl', NULL),
  ('BERNARDITA LUCO', 'ventas@eltorreon.cl', 'EL TORREON'),
  ('BIANCA TRUJILLO', 'bianca.trujillo@naturesouth.cl', 'NATURE SOUTH'),
  ('CAMILA JARABRÁN', 'cjarabran@fruitandesur.cl', NULL),
  ('CAMILA MÉNDEZ', 'comex@greenex.cl', 'GREENEX'),
  ('CARLOS SAA', 'carlos.saa@blumar.com', 'BLUMAR'),
  ('CECILIA GUZMAN', 'cguzman@coexca.cl', 'COEXCA'),
  ('CECILIA ROSAS', 'cecilia.rosas@cookeaqua.com', 'COOKE AQUA'),
  ('CLAUDIA DUARTE', 'cduarte@chilfresh.cl', 'CHILFRESH'),
  ('CLAUDIA HUERTA', 'claudia.huerta@almafruit.cl', 'ALMA FRUIT'),
  ('CRISTIAN BAHAMONDES', 'cbahamondes@pompeiatrade.cl', 'POMPEIA TRADE'),
  ('CRISTIAN FULLER', 'cfuller@losnobles.cl', 'LOS ROBLES'),
  ('CRISTIAN LÓPEZ', 'clopez@fruitandesur.cl', 'FRUIT ANDES FRUIT'),
  ('CRISTIAN MORRIS', 'cristianm@thegrowers.club', 'THE GROWERS CLUB'),
  ('CRISTIAN MUÑOZ', 'cristian.munoz@mowi.com', 'MOWI'),
  ('CRISTIAN PINOCHET', 'cpinochet@cindependencia.cl', 'AGRÍCOLA INDEPENDENCIA'),
  ('CRISTOBAL CARDENAS', 'araya.cardenas.cristobal@gmail.com', 'ESPERANZA VERDE'),
  ('CRISTOBAL LOZANO', 'cristoballozano@agricolals.com', 'AGRÍCOLA LS'),
  ('D ROJAS', 'drojas@leice.cl', 'AGRÍCOLA INDEPENDENCIA'),
  ('DANIEL SAINT MARTIN', 'daniel@pai-argentina.com', 'PAI ARGENTINA'),
  ('DANIEL SALDIVIA', 'daniel.saldivia@ulmoltda.cl', 'ULMO'),
  ('DAVID MANCILLA', 'demancilla@patagoniaoceanfood.cl', 'PATAGONIA OCEAN FOOD'),
  ('DIEGO VELASQUEZ', 'dvelasquez@multi-xsalmon.com', 'MULTIEXPORT'),
  ('EDUARDO MONTENEGRO', 'emontenegro@redandblueberries.cl', 'RED & BLUEBERRIES'),
  ('ELIA PEZO', 'epezo@integrachile.com', 'INTEGRA CHILE'),
  ('ENRIQUE LORDA', 'elorda@kleppe.com.ar', 'KLEPPE'),
  ('ERTAN ERTAS', 'ertanertas33@gmail.com', NULL),
  ('FACUNDO QUIROS', 'facundoquiros@yahoo.com', 'CÁMARA DE CEREZAS DE MENDOZA'),
  ('FELIPE LARENAS', 'flarenas@vifchile.cl', 'VIF CHILE'),
  ('FELIPE QUILODRAN', 'felipe.quilodran@fiordoaustral.com', 'FIORDO AUSTRAL'),
  ('FÉLIX ESCOBAR', 'fescobar@dfaneuquen.com', 'DEPÓSITO FISCAL DE NEUQUEN'),
  ('FERNANDA ORTIZ', 'fernanda.ortiz@aysenpacific.com', 'AYSEN PACIFIC'),
  ('FERNANDO MERCADO', 'fernando@fruitsexport.cl', 'FRUITS EXPORT'),
  ('FRANCISCA DIAZ', 'fdiaz@coexca.cl', 'COEXCA'),
  ('FRANCISCO ASTABURUAGA', 'fastaburuaga@xsur.cl', 'X SUR'),
  ('GABRIEL OJEDA', 'gabriel.ojeda@mowi.com', 'MOWI'),
  ('GENOVEVA VOLKE', 'exportaciones@southwind.cl', NULL),
  ('GERMAN VERGARA', 'administracion@pacificseachile.com', 'PACIFIC SEA'),
  ('HANS LEIBBRANDT', 'hans.leibbrandt@monfrut.cl', 'MONFRUT'),
  ('HERNÁN DE BELLIS', 'hdebellis@extraberries.com', 'EXTRA BERRIES'),
  ('J OYARZO', 'joyarzo@acmechile.com', 'ACME CHILE'),
  ('JAVIER FRIAS', 'javierasesorias@jcomex.cl', 'JCOMEX'),
  ('JENNY GONZÁLEZ', 'jennygonzalez@agricolals.com', 'AGRÍCOLA LS'),
  ('JESSICA MARTÍNEZ', 'jmartinez@patagonfoods.cl', 'PATAGON FOODS'),
  ('JIN AMER', 'amer_jm@outlook.com', NULL),
  ('JORGE SALHUS', 'jorge.salhus@exportadoravientosdelsur.cl', 'EXPORTADORA VIENTOS DEL SUR'),
  ('JOSÉ MOLINA', 'ecomex@eltorreon.cl', 'EL TORREÓN'),
  ('JOSEFA CARDEMIL', 'jcardemil@alimex.cl', 'ALIMEX'),
  ('JUAN BUSTAMANTE', 'jbustamante@vifchile.cl', 'VIF CHILE'),
  ('JUAN MIGUEL OVALLE', 'jmovalle@apfrut.cl', 'AP FRUT'),
  ('JUAN PABLO ZHANGH', 'jpz@hillvillagroup.com', 'HILLVILLA'),
  ('JULIO CAMPILLO', 'jcampillo@fruttita.cl', 'FRUTTITA'),
  ('KEVIN FOXLEY', 'kevin@globalfruit.org', 'GLOBALFRUIT'),
  ('KEVIN MUÑOZ', 'soporte.logistica@copefrut.com', 'COPEFRUT'),
  ('LETICIA ULLOA', 'leticia.ulloa@purenaturecl.com', 'PURE NATURE'),
  ('LOGÍSTICA TENO FRUIT', 'logistica@tenofruit.com', NULL),
  ('LORENZO LEÓN', 'lorenzo@cleequality.com', 'EXPORTADORA LOS LIRIOS'),
  ('MABEL ARANCIBIA', 'comex@exportadoravientosdelsur.cl', 'EXPORTADORA VIENTO DEL SUR'),
  ('MAGDALENA TORO', 'mtoro@xsur.cl', 'X SUR'),
  ('MARCELA LÓPEZ', 'marcela.lopez@monfrut.cl', 'MONFRUT'),
  ('MARCELA TAPIA', 'mtapia@bluesea.cl', 'BLUE SEA'),
  ('MARCO MADRIAGA', 'mmadriaga@jotrisa.cl', 'JOTRISA'),
  ('MARCO VERGARA', 'mvergara@jotrisa.cl', 'JOTRISA'),
  ('MARIANO TAPPATA', 'mtappata@pai-argentina.com', 'PAI ARGENTINA'),
  ('MARIO ALMENDRA', 'malmendra@valle-maule.cl', 'VALLE MAULE'),
  ('MARIO BRUNA', 'mbruna@mjtrading.cl', 'MJ TRADING'),
  ('MARISOL NAVARRO', 'marisol.navarro@naturesouth.cl', 'NATURE SOUTH'),
  ('MARLEN ROCHA CEA', 'mrochacea@familygrowerschile.cl', NULL),
  ('MARLON JIMENEZ', 'marlon.jimenez@frutasol.cl', 'FRUTASOL'),
  ('MATIAS BENAVIDES', 'matias@mormanagementgroup.com', NULL),
  ('MATIAS CHAVARRÍA', 'mchavarria@marinefarm.cl', 'MARINE FARM'),
  ('MATIAS UNQUÉN', 'munquen@rinofruit.com', 'RINOFRUIT'),
  ('MATIAS VELOSO', 'matias@fruitsexport.cl', 'FRUITS EXPORT'),
  ('MAX', 'max@aqua-link.cl', 'AQUALINK'),
  ('MAY ZHAO', 'may@yemete.com', 'YEMETE'),
  ('MIGUEL ANGEL LORENZZINI', 'miguel@tenofruit.com', 'TENO FRUIT'),
  ('MIGUEL HERNANDEZ', 'mhernandez@pai-argentina.com', 'PAI ARGENTINA'),
  ('MIGUEL VERGARA', 'mvergara@redandblueberries.cl', 'RED & BLUEBERRIES'),
  ('MIREN ECEIZA', 'miren.eceiza@primland.fr', 'PRIMLAND'),
  ('MIRTA YAÑEZ', 'logistica@expoagrosol.com', 'AGROSOL'),
  ('NICOLAS BONAVENTO', 'nbonavento@mazul.com.ar', 'MOÑO AZUL'),
  ('NICOLAS CORREA', 'nicolas@fruticolalareserva.com', 'EXPORTADORA LA RESERVA'),
  ('NICOLHE MENESES', 'nmeneses@rinofruit.com', 'RINOFRUIT'),
  ('OSVALDO', 'osvaldo.cristian@gmail.com', NULL),
  ('PABLO OSETE', 'p.osete@kleppe.com.ar', 'KLEPPE'),
  ('PABLO PIZZARRO', 'pablopizarro@yemete.com', 'YEMETE'),
  ('PATRICIA RUIZ', 'patricia.ruiz@vrfoods.cl', 'VR FOODS'),
  ('PATRICIO BORLANDO', 'pborlando@fruitandesur.cl', 'FRUIT ANDESUR'),
  ('PATRICIO CARREÑO', 'pcarreno@greenex.cl', 'GREENEX'),
  ('PATRICIO PÉREZ', 'patricio.perez@cookeaqua.com', 'COOK AQUA'),
  ('PAULA FUENZALIDA', 'pfuenzalida@chilfresh.cl', 'CHILFRESH'),
  ('RENÉ TEMPE', 'rene.tampe@ulmoltda.cl', 'ULMO'),
  ('RICARDO FERNÁNDEZ', 'ricardo@exportecoterra.cl', 'EXPORTADORA ECOTERRA'),
  ('RICARDO NUÑEZ', 'rnunez@freshland.cl', 'FRESH LAND'),
  ('RODRIGO LÓPEZ', 'rlopez@rinofruit.com', 'RINOFRUIT'),
  ('RODRIGO MATUS', 'rodrigo@vrfoods.cl', 'VR FOODS'),
  ('RODRIGO SOTOMAYOR', 'rodrigo@portalmaule.com', 'PORTAL MAULE (AGROSOL)'),
  ('ROMINA SESTI', 'rsesti@pft.com.ar', 'MOÑO AZUL'),
  ('S KAHN', 'skahn@albilbao.cl', 'ALIMENTOS BILBAO'),
  ('SANDRA ALVARADO', 'salvarado@noblefruit.cl', 'NOBLE FRUIT'),
  ('SEBASTIÁN CHAMBLAT', 'schamblat@sclem.cl', 'SAN CLEMENTE'),
  ('SHEILA JACKSON', 'sheilajackson@agricolals.com', 'AGRÍCOLA LS'),
  ('SUSSAN PÉREZ', 'sperez@apfrut.cl', 'AP FRUT'),
  ('TAMARA NAVARRETE', 'tamara.navarrete@blumar.com', 'BLUMAR'),
  ('THOMAS GRAELL', 'thomas.graell@monfrut.cl', 'MONFRUT'),
  ('VALENTINA MIRANDA', 'vmiranda@blossom.cl', 'BLOSSOM'),
  ('VICTOR', 'operacionmantencion@hillvillagroup.com', NULL),
  ('VICTOR ANDRAE', 'vandrade@aquachile.com', 'AQUACHILE'),
  ('VÍCTOR BRAVO', 'victor.bravo@copefrut.com', 'COPEFRUT'),
  ('VÍCTOR MAROTO', 'victor.maroto@fruttita.cl', 'FRUTTITA'),
  ('XIMENA NAVARRETE', 'ximena.navarrete@copefrut.com', 'COPEFRUT'),
  ('ZAID ALTHAFEER', 'zalthafeer@gmail.com', 'RUTA DE LA FRUTA')
  ON CONFLICT (email) DO UPDATE SET
    nombre = EXCLUDED.nombre,
    empresa = COALESCE(EXCLUDED.empresa, public.informaciones_contactos.empresa),
    activo = true
  RETURNING id
)
INSERT INTO public.informaciones_grupo_miembros (grupo_id, contacto_id)
SELECT g.id, i.id
FROM grupo g
CROSS JOIN ins i
ON CONFLICT DO NOTHING;
