-- ============================================================================
-- SEED: Destinos (POD - Port of Discharge)
-- ============================================================================

-- ─── CREAR TABLA ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS destinos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre TEXT NOT NULL UNIQUE,
  pais TEXT,
  codigo_puerto TEXT,
  activo BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_destinos_activo ON destinos(activo);
CREATE INDEX IF NOT EXISTS idx_destinos_pais ON destinos(pais);

-- ─── INSERTAR DESTINOS ───────────────────────────────────────────────────────

INSERT INTO destinos (nombre) VALUES
  ('ACAJUTLA'),
  ('AD DAMMAN'),
  ('ADELAIDE'),
  ('AL KHOMS'),
  ('ALGECIRAS'),
  ('AMBARLI'),
  ('AMBARLI PORT ISTANBUL'),
  ('ANTWERP'),
  ('AQABA'),
  ('AUBURN'),
  ('AUCKLAND METROPORT'),
  ('BALBOA'),
  ('BANGKOK'),
  ('BARCELONA'),
  ('BARRANQUILLA'),
  ('BARRANQUILLAS'),
  ('BEIRUT'),
  ('BILBAO'),
  ('BREMERHAVEN'),
  ('BRISBANE'),
  ('BUENAVENTURA'),
  ('BUSAN'),
  ('CADILLAC'),
  ('CALDERA'),
  ('CALLAO'),
  ('CALUMET CITY'),
  ('CAPE TOWN'),
  ('CARTAGENA'),
  ('CARTAGO'),
  ('CAUCEDO'),
  ('CHARLESTON'),
  ('CHARLESTON NORTH'),
  ('CHENGDU'),
  ('CHICAGO'),
  ('CIVITAVECCHIA'),
  ('COLON'),
  ('CORINTO'),
  ('CORNWALL'),
  ('CRISTOBAL'),
  ('DOHA'),
  ('DUBLIN'),
  ('EL CISNE'),
  ('EL TEJAR'),
  ('ESKILSTUNA'),
  ('FELIXSTOWE'),
  ('FOS SUR MER'),
  ('FREEPORT'),
  ('FREMANTLE'),
  ('GDANSK'),
  ('GEBZE'),
  ('GENOA VADO LIGURE'),
  ('GENOVA'),
  ('GREENFIELD'),
  ('GUANGZHOU'),
  ('GUATEMALA CITY'),
  ('GUAYAQUIL'),
  ('GUAYAQUIL-POSORJA'),
  ('HAIPHONG'),
  ('HAKATA'),
  ('HALTON HILLS'),
  ('HAMAD'),
  ('HAMBURG'),
  ('HAMBURGO'),
  ('HART'),
  ('HEFEI'),
  ('HELSINGBORG'),
  ('HELSINKI'),
  ('HEREDIA'),
  ('HO CHI MINH CITY'),
  ('HONG KONG'),
  ('HOUSTON'),
  ('IZMIR'),
  ('IZMIT KORFEZI'),
  ('JAKARTA'),
  ('JEBEL ALI'),
  ('JEDDAH'),
  ('KAOHSIUNG'),
  ('KEELUNG'),
  ('KING ABDULLAH'),
  ('KING ABDULLAH PORT'),
  ('KOBE'),
  ('KRISTIANSAND'),
  ('LA GUAIRA'),
  ('LAEM CHABANG'),
  ('LAKE WALES'),
  ('LAS PALMAS'),
  ('LEBANON'),
  ('LEGHORN'),
  ('LIMASSOL'),
  ('LISBOA'),
  ('LISBON'),
  ('LIVORNO'),
  ('LONDON GATEWAY'),
  ('LONG BEACH'),
  ('LOS ANGELES'),
  ('LYTTELTON'),
  ('MAASVLAKTE'),
  ('MALTA'),
  ('MANAGUA'),
  ('MANAWA'),
  ('MANZANILLO - MÉXICO'),
  ('MANZANILLO - PANAMÁ'),
  ('MARIN'),
  ('MARSEILLE'),
  ('MATAGALPA'),
  ('MELBOURNE'),
  ('MEMPHIS'),
  ('MERSIN'),
  ('MISURATAH'),
  ('MONTREAL'),
  ('NAGOYA'),
  ('NANSHA'),
  ('NANSHA NEW PORT'),
  ('NAPIER'),
  ('NEW YORK'),
  ('NEWARK'),
  ('NHAVA SHEVA'),
  ('NINGBO'),
  ('NORFOLK'),
  ('OSLO'),
  ('PAITA'),
  ('PHILADELPHIA'),
  ('PIRAEUS'),
  ('PISCO'),
  ('PORT EVERGLADES'),
  ('PORT HUENEME'),
  ('PORT KLANG'),
  ('PORT SAID WEST'),
  ('PUERTO CABELLO'),
  ('PUERTO CALDERA'),
  ('PUERTO CORTES'),
  ('PUERTO LIMON'),
  ('PUERTO MOIN'),
  ('PUERTO QUETZAL'),
  ('PUSAN'),
  ('QINGDAO'),
  ('RANCHO DOMINGUEZ'),
  ('RIGA'),
  ('RODMAN'),
  ('ROTTERDAM'),
  ('SALERNO'),
  ('SALVADOR'),
  ('SAN JUAN'),
  ('SAN PEDRO SULA'),
  ('SAN SALVADOR'),
  ('SAVANNAH'),
  ('SFAX'),
  ('SHANGHAI'),
  ('SHEKOU'),
  ('SHENZHEN'),
  ('SHUWAIKH'),
  ('SINES'),
  ('SINGAPORE'),
  ('SOHAR'),
  ('SOUTHAMPTON'),
  ('ST. PETESBURGO'),
  ('STANFORD-LE-HOPE'),
  ('SUAPE'),
  ('SYDNEY'),
  ('TAIPEI'),
  ('TALLINN'),
  ('TAURANGA'),
  ('TEGUCIGALPA'),
  ('TENERIFE'),
  ('THESSALONIKI'),
  ('TORONTO'),
  ('VALENCIA'),
  ('VIGO'),
  ('VLISSINGEN'),
  ('WILLEMSTAD'),
  ('XIAMEN'),
  ('YANGPU'),
  ('YANTIAN'),
  ('YOKOHAMA'),
  ('ZAMBRANO')
ON CONFLICT (nombre) DO NOTHING;
