-- ============================================================================
-- Actualizar destinos con sus países correspondientes
-- ============================================================================

UPDATE destinos SET pais = 'EL SALVADOR' WHERE nombre = 'ACAJUTLA';
UPDATE destinos SET pais = 'ARABIA SAUDITA' WHERE nombre = 'AD DAMMAN';
UPDATE destinos SET pais = 'AUSTRALIA' WHERE nombre = 'ADELAIDE';
UPDATE destinos SET pais = 'LIBIA' WHERE nombre = 'AL KHOMS';
UPDATE destinos SET pais = 'ESPAÑA' WHERE nombre = 'ALGECIRAS';
UPDATE destinos SET pais = 'TURQUÍA' WHERE nombre IN ('AMBARLI', 'AMBARLI PORT ISTANBUL');
UPDATE destinos SET pais = 'BÉLGICA' WHERE nombre = 'ANTWERP';
UPDATE destinos SET pais = 'JORDANIA' WHERE nombre = 'AQABA';
UPDATE destinos SET pais = 'ESTADOS UNIDOS' WHERE nombre IN ('AUBURN', 'CALUMET CITY', 'CHARLESTON', 'CHARLESTON NORTH', 'CHICAGO', 'GREENFIELD', 'HART', 'HOUSTON', 'LAKE WALES', 'LONG BEACH', 'LOS ANGELES', 'MEMPHIS', 'NEW YORK', 'NEWARK', 'NORFOLK', 'PHILADELPHIA', 'PORT EVERGLADES', 'PORT HUENEME', 'RANCHO DOMINGUEZ', 'SAVANNAH');
UPDATE destinos SET pais = 'NUEVA ZELANDA' WHERE nombre IN ('AUCKLAND METROPORT', 'LYTTELTON', 'NAPIER', 'TAURANGA');
UPDATE destinos SET pais = 'PANAMÁ' WHERE nombre IN ('BALBOA', 'COLON', 'CRISTOBAL', 'MANZANILLO - PANAMÁ', 'RODMAN');
UPDATE destinos SET pais = 'TAILANDIA' WHERE nombre IN ('BANGKOK', 'LAEM CHABANG');
UPDATE destinos SET pais = 'ESPAÑA' WHERE nombre IN ('BARCELONA', 'BILBAO', 'LAS PALMAS', 'MARIN', 'TENERIFE', 'VALENCIA', 'VIGO');
UPDATE destinos SET pais = 'COLOMBIA' WHERE nombre IN ('BARRANQUILLA', 'BARRANQUILLAS', 'BUENAVENTURA', 'CARTAGENA');
UPDATE destinos SET pais = 'LÍBANO' WHERE nombre IN ('BEIRUT', 'LEBANON');
UPDATE destinos SET pais = 'ALEMANIA' WHERE nombre IN ('BREMERHAVEN', 'HAMBURG', 'HAMBURGO');
UPDATE destinos SET pais = 'AUSTRALIA' WHERE nombre IN ('BRISBANE', 'FREMANTLE', 'MELBOURNE', 'SYDNEY');
UPDATE destinos SET pais = 'COREA DEL SUR' WHERE nombre IN ('BUSAN', 'PUSAN');
UPDATE destinos SET pais = 'COSTA RICA' WHERE nombre IN ('CALDERA', 'CARTAGO', 'HEREDIA', 'PUERTO CALDERA', 'PUERTO LIMON', 'PUERTO MOIN');
UPDATE destinos SET pais = 'PERÚ' WHERE nombre IN ('CALLAO', 'PAITA', 'PISCO');
UPDATE destinos SET pais = 'SUDÁFRICA' WHERE nombre = 'CAPE TOWN';
UPDATE destinos SET pais = 'REPÚBLICA DOMINICANA' WHERE nombre = 'CAUCEDO';
UPDATE destinos SET pais = 'CHINA' WHERE nombre IN ('CHENGDU', 'GUANGZHOU', 'HEFEI', 'HONG KONG', 'NANSHA', 'NANSHA NEW PORT', 'NINGBO', 'QINGDAO', 'SHANGHAI', 'SHEKOU', 'SHENZHEN', 'XIAMEN', 'YANGPU', 'YANTIAN');
UPDATE destinos SET pais = 'ITALIA' WHERE nombre IN ('CIVITAVECCHIA', 'GENOA VADO LIGURE', 'GENOVA', 'LEGHORN', 'LIVORNO', 'SALERNO');
UPDATE destinos SET pais = 'NICARAGUA' WHERE nombre IN ('CORINTO', 'MANAGUA', 'MATAGALPA');
UPDATE destinos SET pais = 'CANADÁ' WHERE nombre IN ('CORNWALL', 'HALTON HILLS', 'MONTREAL', 'TORONTO');
UPDATE destinos SET pais = 'QATAR' WHERE nombre IN ('DOHA', 'HAMAD');
UPDATE destinos SET pais = 'IRLANDA' WHERE nombre = 'DUBLIN';
UPDATE destinos SET pais = 'GUATEMALA' WHERE nombre IN ('EL CISNE', 'EL TEJAR', 'GUATEMALA CITY', 'PUERTO QUETZAL');
UPDATE destinos SET pais = 'SUECIA' WHERE nombre IN ('ESKILSTUNA', 'HELSINGBORG');
UPDATE destinos SET pais = 'REINO UNIDO' WHERE nombre IN ('FELIXSTOWE', 'LONDON GATEWAY', 'SOUTHAMPTON', 'STANFORD-LE-HOPE');
UPDATE destinos SET pais = 'FRANCIA' WHERE nombre IN ('FOS SUR MER', 'MARSEILLE');
UPDATE destinos SET pais = 'BAHAMAS' WHERE nombre = 'FREEPORT';
UPDATE destinos SET pais = 'POLONIA' WHERE nombre = 'GDANSK';
UPDATE destinos SET pais = 'TURQUÍA' WHERE nombre IN ('GEBZE', 'IZMIR', 'IZMIT KORFEZI', 'MERSIN');
UPDATE destinos SET pais = 'ECUADOR' WHERE nombre IN ('GUAYAQUIL', 'GUAYAQUIL-POSORJA');
UPDATE destinos SET pais = 'VIETNAM' WHERE nombre IN ('HAIPHONG', 'HO CHI MINH CITY');
UPDATE destinos SET pais = 'JAPÓN' WHERE nombre IN ('HAKATA', 'KOBE', 'NAGOYA', 'YOKOHAMA');
UPDATE destinos SET pais = 'FINLANDIA' WHERE nombre = 'HELSINKI';
UPDATE destinos SET pais = 'INDONESIA' WHERE nombre = 'JAKARTA';
UPDATE destinos SET pais = 'EMIRATOS ÁRABES UNIDOS' WHERE nombre = 'JEBEL ALI';
UPDATE destinos SET pais = 'ARABIA SAUDITA' WHERE nombre IN ('JEDDAH', 'KING ABDULLAH', 'KING ABDULLAH PORT');
UPDATE destinos SET pais = 'TAIWÁN' WHERE nombre IN ('KAOHSIUNG', 'KEELUNG', 'TAIPEI');
UPDATE destinos SET pais = 'NORUEGA' WHERE nombre IN ('KRISTIANSAND', 'OSLO');
UPDATE destinos SET pais = 'VENEZUELA' WHERE nombre IN ('LA GUAIRA', 'PUERTO CABELLO');
UPDATE destinos SET pais = 'CHIPRE' WHERE nombre = 'LIMASSOL';
UPDATE destinos SET pais = 'PORTUGAL' WHERE nombre IN ('LISBOA', 'LISBON', 'SINES');
UPDATE destinos SET pais = 'PAÍSES BAJOS' WHERE nombre IN ('MAASVLAKTE', 'ROTTERDAM', 'VLISSINGEN');
UPDATE destinos SET pais = 'MALTA' WHERE nombre = 'MALTA';
UPDATE destinos SET pais = 'ESTADOS UNIDOS' WHERE nombre = 'MANAWA';
UPDATE destinos SET pais = 'MÉXICO' WHERE nombre = 'MANZANILLO - MÉXICO';
UPDATE destinos SET pais = 'LIBIA' WHERE nombre = 'MISURATAH';
UPDATE destinos SET pais = 'INDIA' WHERE nombre = 'NHAVA SHEVA';
UPDATE destinos SET pais = 'GRECIA' WHERE nombre IN ('PIRAEUS', 'THESSALONIKI');
UPDATE destinos SET pais = 'MALASIA' WHERE nombre = 'PORT KLANG';
UPDATE destinos SET pais = 'EGIPTO' WHERE nombre = 'PORT SAID WEST';
UPDATE destinos SET pais = 'HONDURAS' WHERE nombre IN ('PUERTO CORTES', 'SAN PEDRO SULA', 'TEGUCIGALPA', 'ZAMBRANO');
UPDATE destinos SET pais = 'LETONIA' WHERE nombre = 'RIGA';
UPDATE destinos SET pais = 'BRASIL' WHERE nombre IN ('SALVADOR', 'SUAPE');
UPDATE destinos SET pais = 'PUERTO RICO' WHERE nombre = 'SAN JUAN';
UPDATE destinos SET pais = 'EL SALVADOR' WHERE nombre = 'SAN SALVADOR';
UPDATE destinos SET pais = 'TÚNEZ' WHERE nombre = 'SFAX';
UPDATE destinos SET pais = 'KUWAIT' WHERE nombre = 'SHUWAIKH';
UPDATE destinos SET pais = 'SINGAPUR' WHERE nombre = 'SINGAPORE';
UPDATE destinos SET pais = 'OMÁN' WHERE nombre = 'SOHAR';
UPDATE destinos SET pais = 'RUSIA' WHERE nombre = 'ST. PETESBURGO';
UPDATE destinos SET pais = 'ESTONIA' WHERE nombre = 'TALLINN';
UPDATE destinos SET pais = 'CURAZAO' WHERE nombre = 'WILLEMSTAD';
